version: "3.5"

networks:
  internal-orderservice:
    name: internal-orderservice

services:
  mongodb:
    hostname: orderservicedb
    image: mongo:4.2.5
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "root"
    networks:
      - internal-orderservice
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:management
    hostname: rabbitmq
    container_name: "rabbitmq"
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "adminpassword"
    ports:
      - "8082:15672"
      - "5672:5672"
    networks:
      - internal-orderservice
