name: Build and Publish AsciiDoc Documentation

on:
  push:
    branches:
      - main
    paths:
      - "src/docs/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0" # or any version that supports your asciidoctor gem

      - name: Install Asciidoctor
        run: |
          gem install asciidoctor

      - name: Build AsciiDoc Documentation
        run: |
          asciidoctor -r asciidoctor-diagram -b html5 -D docs src/docs/asciidoc/index.adoc

      - name: Commit files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add docs/*
          git commit -m "Update GitHub Pages documentation" -a || echo "No changes to commit"
          git push origin main
